application: simpleblog
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: blog/media/img/favicon.ico
  upload: blog/media/img/favicon.ico

- url: /robots.txt
  static_files: blog/media/robots.txt
  upload: blog/media/robots.txt
  
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /static/blog
  static_dir: blog/media
  expiration: '0'

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /.*
  script: djangoappengine/main/main.py
