application: mikebull-simpleblog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /favicon.ico
  static_files: blog/media/img/favicon.ico
  upload: blog/media/img/favicon.ico

- url: /robots.txt
  static_files: blog/media/robots.txt
  upload: blog/media/robots.txt
  
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /static/blog
  static_dir: blog/media
  expiration: '0'

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application
